// --- SERVER CONFIGURATION --- //
#define     SERVER_NAME         "OverZone"
#define     SERVER_LANGUAGE     "Español"
#define     SERVER_GAMEMODE     "Super Zone"
#define     SERVER_HOSTNAME     "[ESP] "SERVER_NAME" - [PC/Android] "SERVER_VERSION""
#define     SERVER_VERSION      "Beta 1.2.1"
#define     SERVER_OWNER        "Jcr_Isra"
#define     SERVER_WEBSITE      "www.overzone.com"

// --- MENSAJES --- //
#define     Mensaje(%0,%1,%2)       SendClientMessage(%0,%1,%2)
#define     MensajeToall(%0,%1)     SendClientMessageToAll(%0,%1)

// colors.inc - paleta de colores RP
#define     COLOR_NEWS          0xFFCC00AA
#define     COLOR_ALERT         0xFF0000AA
#define     COLOR_INFO          0x00CCFFAA
#define     COLOR_VERDE         0x00FF00AA
#define 	COLOR_BLANCO        0xFFFFFFAA
#define     COLOR_GRIS          0xAAAAAAFF
#define     COLOR_SERVIDOR1      0x00BCF5FF 

// --- COLORS HEX --- //
#define     COLOR_SERVIDOR         "{00BCF5}"
#define     COLOR_AMARILLO         "{F1F500}"
#define     COLOR_HEX_VERDE        "{00F508}"
#define     COLOR_HEX_ROJO         "{FF0000}"
#define     COLOR_HEX_BLANCO       "{FFFFFF}"   


// --- DATABASE CONFIGURATION --- //
#define DB_HOST "localhost"
#define DB_USER "root"
#define DB_PASS ""
#define DB_NAME "overzone"

// --- STATS --- // 
#define STATS_LEVEL	    (1)
#define STATS_DINERO 	(16000)
#define STATS_COINS     (0)

// --- ECONOMY --- //
#define COIN_VALUE 45000 // 1 coin (Petro) = 45000$
#define TAX_PERCENT 5    // impuesto general en porcentaje (5%)

// Licencias (precios en coins)
#define LICENSE_DRIVER_PRICE 1
#define LICENSE_WEAPON_PRICE 5
#define LICENSE_BUSINESS_PRICE 20

// License bits
#define LIC_DRIVER 1
#define LIC_WEAPON 2
#define LIC_BUSINESS 4

// --- PLAYER INFO INDICES --- //
#define MAX_CLAVE 129
#define MAX_CORREO 64

// --- DIALOGS --- //

// Estadísticas player dialog


